import { Activity, FileItem, Folder, Message, Notification, Profile, Project, Submission } from '../types/database';

export const mockProfiles: Profile[] = [
  {
    id: 'user-admin',
    user_id: 'auth-user-admin',
    full_name: 'Alexandre Roy',
    email: 'direction@tuwshiuah.com',
    role: 'admin',
    gender: 'male',
    job_title: 'Directeur Général & Fondateur',
    avatar_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAnB8-LrzApQulqNkPJbPdGprKfPsV6m6e_qy5NnWlvXmetrpKzZfK_0XcEXlb9H_hJRcf6Uh_QLQDhX26YKcGxMnpdhkUbmln8uliAQkRb6itVjrnyOxX5iAsh2dO31ZdQeeHQbGF8AwNcSEHiZSLfhRqjvfATw0LwX8jbI8JLqYRkb0LVdVA8A8RHx6b5a9juSNpGWhU68laTs8dKx492aA_k0OVTtQOUX_RBoGXIJP9mnV5GqAZngg',
    is_online: true,
    phone: '+33 6 12 34 56 78',
    created_at: '2026-01-01T08:00:00Z',
  },
  {
    id: 'user-lucas',
    user_id: 'auth-user-lucas',
    full_name: 'Lucas Morel',
    email: 'lucas.m@tuwshiuah.com',
    role: 'employee',
    gender: 'male',
    job_title: 'Ingénieur Deep Learning & NLP',
    avatar_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBLFUmtgVBduZKwpT1DankUT6xH_putNWgDX3nN6f7SkzCSfyIdLWLZTm1LWiKqh1wAhj0jwbxRjflVKDoZRLrgULLMwFARwMuJeoeWjbvyf3su4C9gjb1Q7bXXNIMosVC8x7BYEMmRKCfQIcDvqplvCK-eLKdX52bAuObirh2JzuDhrzFRsmeJsZ3Pax4cwU_BA8ntlINNI1XJIseJmWFGDD7KsQxvp22Wvi9lifU6aS-_oH0x4n_RLQ',
    is_online: true,
    phone: '+33 6 23 45 67 89',
    created_at: '2026-01-15T09:00:00Z',
  },
  {
    id: 'user-thomas',
    user_id: 'auth-user-thomas',
    full_name: 'Thomas Laurent',
    email: 'thomas.l@tuwshiuah.com',
    role: 'employee',
    gender: 'male',
    job_title: 'Lead Developer & DevOps Core',
    avatar_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA0DOlxvloCAHwqXgFydMdJ3-YbrHwTE9jH7X89MvPUHdgxSFF7mcUdcAQ4hTL0wfYPSDFSZYxkfUywo3NYdFJp0VB6WeLtq8fCaHlqrISmiY7v6w171m6Lt1K_CbqwOzp24SFjFwMU_Bdgxdbga-DJCUnWdebeZezIFKUkqWu1dZY3kA95qkUTm8qPpLzw5ADwUPA6ezh5CfWxIOcYh5CeuWDfYUkZRwHlqwxUN8URzCtyE5xoTsW5gA',
    is_online: true,
    phone: '+33 6 34 56 78 90',
    created_at: '2026-02-01T09:00:00Z',
  },
  {
    id: 'user-sarah',
    user_id: 'auth-user-sarah',
    full_name: 'Sarah Benali',
    email: 'sarah.b@tuwshiuah.com',
    role: 'employee',
    gender: 'female',
    job_title: 'Data Scientist & Vision AI',
    avatar_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuALvI3IFPwuJ7wQIOHx6DsgVnWeedKWmjbviHzTqfHZwsyXk3VpnWh51AnB2f3CsVHe0nbekOOSfWAPqjfY4SeZEwpK-0swgAV1z6V2eMhlh8IRzym_Lqo9HNBdgdIafC_K2Kmu8CjbrHdu6xMIqjDTlZU2LZwttLpOIhmm8uabjseRPnmjb3bu2SpCZB6f5EnVFKIiVXHZ3-R5b8_ZEjlaiyFq4MIivmqoLaPbILvAU5OgGZfkWDqeUg',
    is_online: true,
    phone: '+33 6 45 67 89 01',
    created_at: '2026-02-15T09:00:00Z',
  },
  {
    id: 'user-julie',
    user_id: 'auth-user-julie',
    full_name: 'Julie Vasseur',
    email: 'julie.v@tuwshiuah.com',
    role: 'employee',
    gender: 'female',
    job_title: 'UI/UX Designer & Frontend Lead',
    avatar_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAf55ekWo1A4IaCtYgnwces4YnJvd5ohlvzi0t2yFlx1320auDPjbN0YozlcLkgMVQ5hGtAi73A6OqkauRu8Y_5C4HjGdxKpvn987ixHms8s2Ze3lNTfZN_iwTuygvPHVUZxc36xnPlAOJxqpbPjMNZuBS2MXVMYFOctoCl8Cap3Yt0DFEnh-CtXnJqDHg-4j0ZM_bT6_2T5UE_ZavagcSZXW9xqZgQp6LpkBe1w3NlA3z_VF8pAgKIAA',
    is_online: true,
    phone: '+33 6 56 78 90 12',
    created_at: '2026-03-01T09:00:00Z',
  },
];

export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    title: 'Plateforme NLP Client Alpha',
    description: 'Traitement sémantique automatisé, extraction d’entités nommées et résumés de contrats légaux haute précision.',
    category: 'Traitement du Langage (NLP)',
    status: 'IN_PROGRESS',
    progress: 75,
    deadline: '2026-11-18T18:00:00Z',
    created_by: 'user-admin',
    created_at: '2026-09-01T10:00:00Z',
    files_count: 24,
    submissions_count: 4,
    members: [mockProfiles[0], mockProfiles[1], mockProfiles[2], mockProfiles[3]],
  },
  {
    id: 'proj-2',
    title: 'Infrastructure Cloud Sécurisée',
    description: 'Déploiement cluster Kubernetes hybride avec chiffrement de bout en bout et conformité RGPD/HDS.',
    category: 'DevOps & Sécurité Cloud',
    status: 'DELAYED',
    progress: 40,
    deadline: '2026-11-12T18:00:00Z',
    created_by: 'user-admin',
    created_at: '2026-09-10T11:00:00Z',
    files_count: 18,
    submissions_count: 2,
    members: [mockProfiles[0], mockProfiles[2]],
  },
  {
    id: 'proj-3',
    title: 'API Gateway Microservices',
    description: 'Orchestration des flux de données internes, routage intelligent et passerelle de haute disponibilité.',
    category: 'Architecture Backend',
    status: 'IN_PROGRESS',
    progress: 90,
    deadline: '2026-11-25T18:00:00Z',
    created_by: 'user-admin',
    created_at: '2026-09-15T09:30:00Z',
    files_count: 32,
    submissions_count: 5,
    members: [mockProfiles[0], mockProfiles[2], mockProfiles[4]],
  },
  {
    id: 'proj-4',
    title: 'Modèle IA Vision - Détection',
    description: 'Réseau de neurones convolutionnel et modèle YOLO fine-tuné pour la détection d’objets en temps réel.',
    category: 'Vision par Ordinateur',
    status: 'IN_PROGRESS',
    progress: 60,
    deadline: '2026-12-05T18:00:00Z',
    created_by: 'user-admin',
    created_at: '2026-09-20T14:00:00Z',
    files_count: 45,
    submissions_count: 3,
    members: [mockProfiles[0], mockProfiles[1], mockProfiles[3]],
  },
  {
    id: 'proj-5',
    title: 'Design System & UI Workspace',
    description: 'Conception de la charte visuelle, des tokens CSS et des composants d’interface pour TUWSHIUAH.',
    category: 'Design & UI/UX',
    status: 'COMPLETED',
    progress: 100,
    deadline: '2026-10-30T18:00:00Z',
    created_by: 'user-admin',
    created_at: '2026-08-01T08:00:00Z',
    files_count: 15,
    submissions_count: 6,
    members: [mockProfiles[0], mockProfiles[4]],
  },
  {
    id: 'proj-6',
    title: 'Migration SI Interne & RAG',
    description: 'Mise en place d’un assistant interne connecté aux bases documentaires de l’agence via Vector Database.',
    category: 'Intelligence Artificielle',
    status: 'TODO',
    progress: 10,
    deadline: '2026-12-20T18:00:00Z',
    created_by: 'user-admin',
    created_at: '2026-10-01T15:00:00Z',
    files_count: 8,
    submissions_count: 0,
    members: [mockProfiles[0], mockProfiles[1], mockProfiles[3]],
  },
];

export const mockFolders: Folder[] = [
  {
    id: 'fld-1',
    project_id: 'proj-1',
    name: '01_Spécifications & Architecture',
    created_by: 'user-admin',
    created_at: '2026-09-02T10:00:00Z',
    files_count: 14,
    total_size: '45 Mo',
  },
  {
    id: 'fld-2',
    project_id: 'proj-1',
    name: '02_Datasets & Annotations',
    created_by: 'user-sarah',
    created_at: '2026-09-05T11:00:00Z',
    files_count: 8,
    total_size: '1.2 Go',
  },
  {
    id: 'fld-3',
    project_id: 'proj-1',
    name: '03_Modèles & Poids (Weights)',
    created_by: 'user-lucas',
    created_at: '2026-09-12T14:30:00Z',
    files_count: 5,
    total_size: '650 Mo',
  },
  {
    id: 'fld-4',
    project_id: 'proj-1',
    name: '04_Livrables & Rapports Direction',
    created_by: 'user-admin',
    created_at: '2026-09-20T16:00:00Z',
    files_count: 6,
    total_size: '28 Mo',
  },
];

export const mockFiles: FileItem[] = [];

export const mockSubmissions: Submission[] = [
  {
    id: 'sub-1',
    project_id: 'proj-1',
    project_title: 'Plateforme NLP Client Alpha',
    submitted_by: 'user-thomas',
    author: mockProfiles[2],
    title: 'Audit Réseau Core & Configuration VPN Sécurisé',
    description: 'Rapport complet d’analyse de vulnérabilité et schéma d’architecture VPN IPsec pour l’infrastructure client.',
    status: 'PENDING',
    reviewed_by: null,
    reviewer: null,
    reviewed_at: null,
    feedback: null,
    created_at: '2026-09-09T09:15:00Z',
    files: [
      {
        id: 'subfile-1',
        submission_id: 'sub-1',
        file_name: 'rapport_audit_tuwshiuah_v1.4.pdf',
        file_size: '4.8 Mo',
        file_url: '#',
        file_type: 'pdf',
      },
      {
        id: 'subfile-2',
        submission_id: 'sub-1',
        file_name: 'topology_network_schema.png',
        file_size: '1.2 Mo',
        file_url: '#',
        file_type: 'image',
      },
    ],
    comments: [],
  },
  {
    id: 'sub-2',
    project_id: 'proj-4',
    project_title: 'Modèle IA Vision - Détection',
    submitted_by: 'user-sarah',
    author: mockProfiles[3],
    title: 'Modèle IA Vision - Détection d’objets optimisé YOLO',
    description: 'Poids du modèle entraîné sur 50 000 images haute résolution, atteignant un score mAP de 0.92.',
    status: 'PENDING',
    reviewed_by: null,
    reviewer: null,
    reviewed_at: null,
    feedback: null,
    created_at: '2026-09-09T09:45:00Z',
    files: [
      {
        id: 'subfile-3',
        submission_id: 'sub-2',
        file_name: 'weights_yolo_finetuned_alpha.bin',
        file_size: '128 Mo',
        file_url: '#',
        file_type: 'binary',
      },
      {
        id: 'subfile-4',
        submission_id: 'sub-2',
        file_name: 'benchmark_inference_speed.json',
        file_size: '22 Ko',
        file_url: '#',
        file_type: 'json',
      },
    ],
    comments: [],
  },
  {
    id: 'sub-3',
    project_id: 'proj-1',
    project_title: 'Plateforme NLP Client Alpha',
    submitted_by: 'user-lucas',
    author: mockProfiles[1],
    title: 'Pipeline RAG avec Vector Database Qdrant',
    description: 'Implémentation du pipeline d’embeddings et d’indexation sémantique avec gestion de cache.',
    status: 'APPROVED',
    reviewed_by: 'user-admin',
    reviewer: mockProfiles[0],
    reviewed_at: '2026-09-08T18:00:00Z',
    feedback: 'Excellent travail Lucas. Les temps de réponse sont sous la barre des 120ms, validé pour intégration.',
    created_at: '2026-09-08T14:00:00Z',
    files: [
      {
        id: 'subfile-5',
        submission_id: 'sub-3',
        file_name: 'pipeline_rag_evaluation.pdf',
        file_size: '3.4 Mo',
        file_url: '#',
        file_type: 'pdf',
      },
    ],
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg-1',
    project_id: 'proj-1',
    sender_id: 'user-admin',
    sender: mockProfiles[0],
    content: 'Bonjour à tous, point rapide : la démo client est avancée à vendredi 14h. Priorité absolue sur la validation des livrables en cours.',
    created_at: '2026-09-09T08:00:00Z',
  },
  {
    id: 'msg-2',
    project_id: 'proj-1',
    sender_id: 'user-lucas',
    sender: mockProfiles[1],
    content: 'Bien reçu M. le Directeur. Le pipeline RAG est prêt et le script de parsing est en cours de validation finale.',
    created_at: '2026-09-09T08:15:00Z',
  },
  {
    id: 'msg-3',
    project_id: 'proj-1',
    sender_id: 'user-sarah',
    sender: mockProfiles[3],
    content: 'J’ai soumis les nouveaux poids du modèle IA de vision pour inspection hiérarchique.',
    created_at: '2026-09-09T09:46:00Z',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    user_id: 'user-admin',
    title: 'Nouveau livrable soumis',
    message: 'Sarah B. a soumis "Modèle IA Vision - Détection" pour validation.',
    type: 'SUBMISSION',
    link: '/submissions',
    is_read: false,
    created_at: '2026-09-09T09:45:00Z',
  },
  {
    id: 'notif-2',
    user_id: 'user-admin',
    title: 'Nouveau livrable soumis',
    message: 'Thomas L. a soumis "Audit Réseau Core & VPN" pour validation.',
    type: 'SUBMISSION',
    link: '/submissions',
    is_read: false,
    created_at: '2026-09-09T09:15:00Z',
  },
  {
    id: 'notif-3',
    user_id: 'user-lucas',
    title: 'Livrable validé par la Direction',
    message: 'Votre travail "Pipeline RAG Qdrant" a été approuvé par Alexandre Roy.',
    type: 'VALIDATION',
    link: '/submissions',
    is_read: true,
    created_at: '2026-09-08T18:00:00Z',
  },
];

export const mockActivities: Activity[] = [
  {
    id: 'act-1',
    project_id: 'proj-4',
    project_title: 'Modèle IA Vision',
    user_id: 'user-sarah',
    user: mockProfiles[3],
    action_type: 'SUBMIT_WORK',
    description: 'a soumis le travail [Modèle IA Vision - Détection]',
    target_name: 'Module Détection Objets',
    created_at: '2026-09-09T09:45:00Z',
  },
  {
    id: 'act-2',
    project_id: 'proj-1',
    project_title: 'Plateforme NLP Client Alpha',
    user_id: 'user-thomas',
    user: mockProfiles[2],
    action_type: 'SUBMIT_WORK',
    description: 'a soumis le travail [Audit Réseau Core & VPN]',
    target_name: 'Audit Sécurité',
    created_at: '2026-09-09T09:15:00Z',
  },
  {
    id: 'act-3',
    project_id: 'proj-2',
    project_title: 'Infrastructure Cloud',
    user_id: 'user-lucas',
    user: mockProfiles[1],
    action_type: 'UPLOAD_FILE',
    description: 'a téléversé [spec_technique_cloud_k8s_v2.pdf]',
    target_name: 'Espace Fichiers Sécurisé',
    created_at: '2026-09-09T08:30:00Z',
  },
  {
    id: 'act-4',
    project_id: 'proj-6',
    project_title: 'Migration SI Interne & RAG',
    user_id: 'user-admin',
    user: mockProfiles[0],
    action_type: 'CREATE_PROJECT',
    description: 'Nouveau projet [Migration SI Interne & RAG] initialisé',
    target_name: 'Direction Générale',
    created_at: '2026-09-09T06:00:00Z',
  },
];
