import {
  // Icônes requises spécifiées par l'utilisateur
  faHouse,
  faUsers,
  faUser,
  faMoneyBill,
  faCreditCard,
  faArrowRightArrowLeft,
  faCalculator,
  faWallet,
  faBuildingColumns,
  faChartColumn,
  faChartLine,
  faCoins,
  faFile,
  faBell,
  faMagnifyingGlass,
  faGear,
  faPlus,
  faPen,
  faTrash,
  faEye,
  faDownload,
  faFileExport,
  faFilter,
  faCalendar,
  faCheck,
  faXmark,
  faArrowLeft,
  faBars,

  // Icônes workspace & interface TUWSHIUAH
  faFolderOpen,
  faFolder,
  faFolderPlus,
  faFileCircleCheck,
  faCloud,
  faCloudArrowUp,
  faCommentDots,
  faComments,
  faClockRotateLeft,
  faCircleCheck,
  faCircleXmark,
  faCircleExclamation,
  faTriangleExclamation,
  faCheckDouble,
  faPaperPlane,
  faCrown,
  faBriefcase,
  faArrowRight,
  faRightFromBracket,
  faEllipsisVertical,
  faRotate,
  faShieldHalved,
  faBuilding,
  faEnvelope,
  faPhone,
  faMicrochip,
  faRobot,
  faTableCells,
  faFileLines,
  faFilePdf,
  faFileCode,
  faFileCsv,
  faHardDrive,
  faSpinner,
  faSliders,
  faChevronDown,
  faChevronRight,
  faChevronLeft,
  faChevronUp,
  faArrowDown,
  faArrowUp,
  faLink,
  faShareNodes,
  faLock,
  faUnlock,
  faReply,
  faCircleUser,
  faFloppyDisk,
  faArrowsUpDown,
  faUserPlus,
  faPaperclip,
  faRocket,
  faHourglassHalf,
  faClock,
  faIdCard,
  faAward,
  faListCheck,
  IconDefinition,
} from '@fortawesome/free-solid-svg-icons';

export const appIcons: Record<string, IconDefinition> = {
  // 1. Spécifications requises
  dashboard: faHouse,
  clients: faUsers,
  users: faUser,
  revenues: faMoneyBill,
  expenses: faCreditCard,
  transactions: faArrowRightArrowLeft,
  accounting: faCalculator,
  accounts: faWallet,
  bank: faBuildingColumns,
  reports: faChartColumn,
  statistics: faChartLine,
  budgets: faCoins,
  documents: faFile,
  notifications: faBell,
  search: faMagnifyingGlass,
  settings: faGear,
  add: faPlus,
  edit: faPen,
  delete: faTrash,
  view: faEye,
  download: faDownload,
  export: faFileExport,
  filter: faFilter,
  calendar: faCalendar,
  validate: faCheck,
  close: faXmark,
  back: faArrowLeft,
  menu: faBars,

  // 2. Navigation & Actions TUWSHIUAH
  home: faHouse,
  projects: faFolderOpen,
  folder_open: faFolderOpen,
  folder: faFolder,
  folder_copy: faFolderOpen,
  create_new_folder: faFolderPlus,
  submissions: faFileCircleCheck,
  rule_folder: faFileCircleCheck,
  files: faCloud,
  cloud: faCloud,
  cloud_upload: faCloudArrowUp,
  messages: faCommentDots,
  chat_bubble: faCommentDots,
  chat: faComments,
  team: faUsers,
  groups: faUsers,
  activity: faClockRotateLeft,
  history: faClockRotateLeft,
  schedule: faClockRotateLeft,

  // 3. Boutons, statuts & retours
  check_circle: faCircleCheck,
  verified: faCircleCheck,
  verified_user: faShieldHalved,
  security: faShieldHalved,
  done_all: faCheckDouble,
  check: faCheck,
  cancel: faCircleXmark,
  error: faCircleXmark,
  warning: faTriangleExclamation,
  save: faFloppyDisk,
  tune: faSliders,
  swap_horiz: faArrowRightArrowLeft,
  swap_vert: faArrowsUpDown,
  more_vert: faEllipsisVertical,
  visibility: faEye,
  visibility_off: faEye,
  rate_review: faPen,
  reply: faReply,
  send: faPaperPlane,
  add_circle: faPlus,
  person_add: faUserPlus,
  person: faUser,
  mail: faEnvelope,
  email: faEnvelope,
  call: faPhone,
  phone: faPhone,
  logout: faRightFromBracket,
  arrow_forward: faArrowRight,
  arrow_right: faArrowRight,
  arrow_back: faArrowLeft,
  arrow_left: faArrowLeft,
  return: faArrowLeft,
  undo: faArrowLeft,
  chevron_right: faChevronRight,
  chevron_left: faChevronLeft,
  chevron_down: faChevronDown,
  expand_more: faChevronDown,
  chevron_up: faChevronUp,
  arrow_down: faArrowDown,
  arrow_up: faArrowUp,
  paperclip: faPaperclip,
  attachment: faPaperclip,
  attach_file: faPaperclip,
  file_upload: faCloudArrowUp,
  zoom_in: faMagnifyingGlass,
  sentiment_satisfied: faCircleUser,
  smile: faCircleUser,
  emoji: faCircleUser,
  hard_drive: faHardDrive,
  storage: faHardDrive,
  circle_exclamation: faCircleExclamation,
  corporate_fare: faBuilding,
  rocket: faRocket,
  rocket_launch: faRocket,
  link: faLink,
  share: faShareNodes,
  lock: faLock,
  unlock: faUnlock,
  sync: faRotate,
  refresh: faRotate,
  spinner: faSpinner,
  progress_activity: faSpinner,
  event: faCalendar,
  timer: faHourglassHalf,
  clock: faClock,
  cloud_sync: faRotate,
  pending_actions: faListCheck,
  badge: faIdCard,
  award: faAward,

  // 4. Rôles (pour remplacer les emojis sans ambiguïté)
  crown: faCrown,
  admin: faCrown,
  briefcase: faBriefcase,
  employee: faBriefcase,

  // 5. Types de fichiers & technologies
  description: faFileLines,
  pdf: faFilePdf,
  picture_as_pdf: faFilePdf,
  code: faFileCode,
  data_object: faFileCode,
  csv: faFileCsv,
  table_chart: faTableCells,
  dataset: faTableCells,
  memory: faMicrochip,
  binary: faMicrochip,
  robot: faRobot,
  smart_toy: faRobot,
  draft: faFile,
  search_off: faMagnifyingGlass,
  folder_off: faFolder,
  sort_by_alpha: faSliders,
  data_usage: faChartColumn,
  image: faFile,
  forum: faComments,
  folder_zip: faFolder,
  archive: faFolder,
  zip: faFolder,
};

export type AppIconName = keyof typeof appIcons;
